#!/bin/sh +x
# /etc/rcS 

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -t tmpfs  tmpfs  /tmp -o noexec,nosuid,nodev
mount -t sysfs  sysfs  /sys
mount -t proc   proc   /proc

mkdir /dev/pts
mount -t devpts devpts /dev/pts

mkdir /dev/shm
mount -t tmpfs  tmpfs  /dev/shm

mount -o noatime -t tmpfs  tmpfs /mnt
mkdir /mnt/nfs

mount -t tmpfs tmpfs /var   
mkdir /var/log
mkdir /var/run
mkdir /var/tmp
mkdir /var/www
mkdir /var/cache

hostname UCanLinux

syslogd 
klogd

cp /root/index.html /var/www/
httpd -h /var/www

telnetd -f /etc/issue

ifup -a

dmesg -n 1
# mount -t nfs -o nolock 192.168.1.17:/opt/riscv/src/sample /mnt/nfs

